
#python train.py -s ../../../3DGS-DR/data/GlossyReal/bear -m output/learnable_test/bear --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1  --train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
#python train.py -s ../../../3DGS-DR/data/GlossyReal/coral -m output/learnable_test/coral --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1 --train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
python train.py -s ../../../3DGS-DR/data/GlossyReal/maneki -m output/glossyreal/maneki --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1 --envmap_max_res 256 #--use_parallax_correction #--train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
python train.py -s ../../../3DGS-DR/data/GlossyReal/bunny -m output/glossyreal/bunny --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1 --envmap_max_res 256 #--use_parallax_correction #--train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000

python train.py -s ../../../3DGS-DR/data/GlossyReal/bear -m output/glossyreal/bear --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1  --envmap_max_res 256 #--use_parallax_correction #--train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
python train.py -s ../../../3DGS-DR/data/GlossyReal/coral -m output/glossyreal/coral --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1 --envmap_max_res 256 #--use_parallax_correction #--train_on_all #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
python train.py -s ../../../3DGS-DR/data/GlossyReal/vase -m output/glossyreal/vase --eval --iterations 50000 --initial 1 --init_until_iter 3000  -r 1 --envmap_max_res 256 --lambda_diffuse_metal 0.05 --train_on_all # --use_parallax_correction #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
